### ISSUE TITLE
[FEATURE] FVTT v12 compatibility

### ISSUE THREAD

**Issue by PwQt** [johnnolan/wild-magic-surge-5e#737]
I assume there won't be that much to do, but could you please make this module v12 compatible?

By that, last update won't download because of it being locked up to v11 maximum.

**Comment by johnnolan** [comment]
## TODO

- [ ] Update to latest dnd5e
- [ ] Update to latest stable foundry build
- [ ] Update TS latest packages
- [ ] Run manual testing and observe logs
- [ ] Apply tests
- [ ] Apply fixes
- [ ] Release
